export const DEFAULTS = {
  preset: 'terminal',
  toc: 'auto',
  tocWordThreshold: 8000,
  minPagesForToc: 3,
  tocTitle: 'Contents',
  docMeta: true,
  dateFormat: 'iso',
  dateLocale: undefined,
  cover: false,
  coverTitle: '',
  coverAuthor: '',
  coverDate: '',
  footer: 'page-numbers',
  sectionNumbering: false,
  paperFormat: 'A4',
  margins: { top: '2cm', bottom: '2cm', left: '2cm', right: '2cm' },
  outputPath: '',
  _pdf: {
    printBackground: true,
    displayHeaderFooter: true,
    headerTemplate: '<div></div>',
    footerTemplate: '<div style="width:100%; font-family:Menlo,monospace; font-size:7px; color:#666; text-align:center; padding:0 2cm;"><span class="pageNumber"></span> / <span class="totalPages"></span></div>',
    viewport: { width: 720, height: 720 },
  },
};
