export const DEFAULTS = {
  preset: 'terminal',
  toc: 'auto',
  tocWordThreshold: 8000,
  minPagesForToc: 3,
  tocTitle: 'Contents',
  docMeta: true,
  dateFormat: 'iso',
  dateLocale: undefined,
  cover: false,
  coverTitle: '',
  coverAuthor: '',
  coverDate: 'auto',
  coverDateText: '',
  footer: 'page-numbers',
  sectionNumbering: false,
  paperFormat: 'A4',
  margins: { top: '2cm', bottom: '2cm', left: '2cm', right: '2cm' },
  mermaidMaxWidth: undefined,
  mermaidMaxHeight: undefined,
  outputPath: '',
};
